name: Publish Docker image

on:
  push:
    # Publish `lcv-restapi` as Docker `latest` image.
    branches:
      - maven-use-case

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  pull_request:
    branches:
      - maven-use-case

env:
  IMAGE_NAME: fasten.lcv.plugin


jobs:

  push:
    runs-on: ubuntu-latest
    name: LCV REST APIs for Fasten

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build image
      run:  docker build -t fasten.lcv.plugin -f DockerfileExternal .
    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME
        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$VERSION" == "maven-use-case" ] && VERSION=${GITHUB_SHA::8}
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        # Push images
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
        docker tag $IMAGE_NAME $IMAGE_ID:latest
        docker push $IMAGE_ID:latest
